import type { Metadata } from "next";

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
import { CartProvider } from "@/lib/Cart-context";
import { userService } from "@/services/auth.service";

export const metadata: Metadata = {
  title: "Food Hub App",
  description: "Generated by FoodHub",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await userService.getSession();
  
  return (
    <html lang="en">
      <body>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
